[project]
name = "nascarapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psutil>=7.0.0",
    "pytz>=2025.2",
    "requests>=2.32.3",
    "sanic>=25.3.0",
]
